on:
  release:
    types: [published, edited]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get ref_name
      run: |
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"
    - name: Get version
      run: |
        VERSION=$(cat version)
        echo "Version name from file: ${VERSION}"
